version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  garie-lighthouse:
    image: "ejoc/garie-lighthouse:latest"
    volumes:
      - ./reports:/usr/src/garie-lighthouse/reports
    ports:
      - 80:3000
    environment:
      - HOST=influxdb
    depends_on:
      - influxdb
# :same as:  - INFLUXDB_URL=http://admin:admin@influxdb:8086/lighthouse
